project_id = "gjexoflqyserxoylrnyp"

[functions.extract-receipt-data]
verify_jwt = true

[functions.send-receipt-notification]
verify_jwt = true

[functions.send-invoice-email]
verify_jwt = true

[functions.send-payment-reminder]
verify_jwt = false
